### PR TITLE
Misc Fixes

### PR DESCRIPTION
**Pull request by thehappydinoa**
- Added [more audio files](https://androidflagship.com/26657-enjoy-stock-oxygen-os-audio-files-on-custom-roms-on-oneplus-3) and fixed perms with others
- Fixed boot animation
- Added min api and arch for apps

### CODE REVIEW

**Comment by MarcAnt01** [comment]
Bootanimation still remains unchanged to me😢.
Can you also target Arm64 devices in app installation as it seems led to bootloop?

**Comment by thehappydinoa** [comment]
@MarcAnt01 where is your boot animation normally? And what do you mean, I just used the apps you already had in your module.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 where is your boot animation normally? And what do you mean, I just used the apps you already had in your module.

Nope, bootloop isn't your fault, it's mine. App are targeted Arm64 and just cause bootloop on Arm32 devices. As for boot animation, does it work for you?

**Comment by thehappydinoa** [comment]
It should be fixed in 826b0bb

**Pull request merged**
